services:
  - type: web
    name: smart-energy-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://smart-energy-backend.onrender.com